### PR TITLE
Update Fortran test generator to handle arbitrary test case nesting a…

### PR DESCRIPTION
**Pull request by IsaacG**
…nd add TOML metadata support

### CODE REVIEW

**Comment by IsaacG** [comment]
@ErikSchierboom would you happen to understand what the failing Windows test is unhappy about?

**Comment by IsaacG** [comment]
@ErikSchierboom A quick Google search suggests the Windows issue might be an issue finding DLL files and not related to the change.

**Review by ErikSchierboom — APPROVED** [review]
LGTM

> @ErikSchierboom A quick Google search suggests the Windows issue might be an issue finding DLL files and not related to the change.

Maybe something for a different PR, or else open an issue?

**Comment by IsaacG** [comment]
There's already #188  which seems to cover this issue :)

**Pull request merged**
