### PR TITLE
Add hiljusti as a maintainer

### PR DESCRIPTION
**Pull request by hiljusti**
So I can help prep for launch, review & merge, etc

### CODE REVIEW

**Review by SaschaMann — APPROVED** [review]

**Comment by iHiD** [comment]
I'll let someone else merge this when it's green, but I've manually added you to the team so you can start reviewing etc :)

**Review by pclausen — APPROVED** [review]

**Comment by pclausen** [comment]
gcc and gfortran got updated on MAC and changed path. Fixed the ci.yml and merged the change. And I learned some more git stuff in the process. :-)

**Comment by pclausen** [comment]
@iHiD Are you "maintainers-admin" ? Seems you are the only person who can merge.

**Comment by hiljusti** [comment]
Looks like only @iHiD or @ErikSchierboom could merge this?

**Review by ErikSchierboom — APPROVED** [review]
Small side note: I would normally suggest to split up this PR into two different PRs, as the content is not really related. But it's fine for now :)

**Comment by ErikSchierboom** [comment]
Welcome as a maintainer @hiljusti! 🎉

**Pull request merged**
